import { computed } from 'vue'

const translations = {
  en: {
    nav: { home: 'Home', search: 'Search', compare: 'Compare', academy: 'Academy', competition: 'Competition', main: 'Main navigation', github: 'TF2Lab on GitHub', brand: 'logs.tf analytics' },
    home: { eyebrow: 'Competitive TF2 analytics', title: 'Play smarter.', titleAccent: 'Improve faster.', description: 'Turn your logs.tf matches into the next training session. Track performance, find patterns, and focus on what moves your game forward.', searchLabel: 'SteamID, player name, or logs.tf URL', placeholder: 'Search SteamID, player, or log URL', analyze: 'Analyze player', hint: 'Try a SteamID64, logs.tf log ID, or player name.', preview: 'TF2Lab analytics preview', live: 'Live match insights', period: 'Last 30 days', score: 'Performance score', matches: 'Recent matches', analyzed: '14 analyzed', features: 'What TF2Lab does', pillars: 'Three pillars built for competitive players', analytics: 'Analytics', analyticsText: 'Deep dive into your logs — K/D trends, damage breakdowns, class usage radars, and performance benchmarks across maps and seasons.', analyticsCta: 'View analytics →', competition: 'Competition', competitionText: 'Track official matches, scrims, and tournaments. Scout opponents, manage team lineups, and prepare with data-driven insights.', competitionCta: 'Explore matches →', academy: 'Academy', academyText: 'Learn competitive TF2 from scratch — guides on configs, HUDs, whitelists, map callouts, and progression from PUGs to leagues.', academyCta: 'Start learning →', edge: 'Find your edge', edgeText: 'See what wins more rounds.', learn: 'Learn from every match', learnText: 'Turn trends into training goals.', built: 'Built for competitive TF2', builtText: 'Focused, useful, and free.', previewLabel: 'TF2Lab analytics preview', live: 'Live match insights', period: 'Last 30 days', score: 'Performance score', analyzed: '14 analyzed', benefits: 'TF2Lab benefits' },
    search: { breadcrumb: 'Search', eyebrow: 'TF2Lab search', title: 'Find players & logs.', description: 'Search by SteamID64, player name, or logs.tf log ID.', label: 'Search', placeholder: 'SteamID, player, or log ID', clear: 'Clear', searching: 'Searching...', search: 'Search', help: 'Press / to focus search and Esc to clear.', unavailable: 'Search temporarily unavailable', unavailableText: "We couldn't reach the logs.tf search service. Check your connection and try again.", retry: 'Try again', primary: 'Primary results', players: 'Players found', exact: 'Exact match', matches: 'Matches', kills: 'Kills', damage: 'Damage', profile: 'View player profile →', secondary: 'Secondary results', related: 'Related logs', hint: 'Related logs found, but no player nick matched this search. Try another alias or the SteamID64.', log: 'Log', map: 'Map', viewLog: 'View log', playerProfile: 'Player profile', openLogs: 'Open on logs.tf ↗', noResults: 'No results for', tryDifferent: 'Try a different SteamID, player name, or log ID.', suggestions: 'Try searching for:', examples: 'Examples:', archive: 'Search the TF2Lab log archive', start: 'Enter a SteamID64, player name, or logs.tf log ID above to start.', previous: '← Previous', page: 'Page', of: 'of', next: 'Next →', openLogs: 'Open on logs.tf ↗', pagination: 'Pagination', examples: 'Examples:', emptySteamId: "This SteamID64 wasn't found in logs.tf. Make sure it's a valid 17-digit SteamID64 (starts with 7656119).", emptyLogId: 'Log ID {id} not found on logs.tf.', emptyPlayer: 'No player cards matched "{name}" in the logs.tf sample. Try an exact alias or SteamID64 for a reliable profile match.' },
    compare: { breadcrumb: 'Compare', eyebrow: 'TF2Lab comparison', title: 'Compare two players.', description: 'Put two SteamID64s side by side and see where each player stands out.', inputPlaceholder: 'Player name or SteamID64', playerA: 'Player A', playerB: 'Player B', window: 'Window', games: 'Last {n} games', compare: 'Compare players', comparing: 'Comparing...', clear: 'Clear', loading: 'Loading comparison', fullProfile: 'View full profile →', summary: 'Quick summary', leads: 'leads in', table: 'Performance comparison', metric: 'Metric', matches: 'Matches', kills: 'Kills', deaths: 'Deaths', damage: 'Damage', heals: 'Heals', choose: 'Choose two players', chooseText: 'Use SteamID64 to create a consistent comparison between TF2Lab profiles.', example: 'Example:', loadExample: 'Load two example players', invalid: 'Enter two valid 17-digit SteamID64s.', same: 'Choose two different players.', failed: 'Could not load one of the profiles. Check the SteamIDs and try again.', none: 'no metrics' },
    player: { search: 'Search', back: 'Back to search', analysisWindow: 'Analysis window', all: 'All', logs: 'logs', analysisWarning: 'Trend analysis needs at least {n} logs to be reliable.', kdPerMatch: 'K/D per match', damagePerMatch: 'Damage per match', healingPerMatch: 'Healing per match', damageByClass: 'Damage by class', notFound: 'Player not found', unavailable: 'No analyzed performance data is available for', reason: 'Reason:', checkSteam: 'Check the SteamID or try a player with public logs.', newSearch: 'New search' },
    log: { search: 'Search', back: 'Back to search', notFound: 'Log not found', unable: "We couldn't load log", reason: 'Reason:', checkId: 'Please check the ID and try again.', newSearch: 'New search' }
  },
  pt: {
    nav: { home: 'Início', search: 'Busca', compare: 'Comparar', academy: 'Academia', competition: 'Competições', main: 'Navegação principal', github: 'TF2Lab no GitHub', brand: 'analytics do logs.tf' },
    home: { eyebrow: 'Analytics competitivo de TF2', title: 'Jogue melhor.', titleAccent: 'Evolua mais rápido.', description: 'Transforme suas partidas do logs.tf na próxima sessão de treino. Acompanhe seu desempenho, encontre padrões e foque no que faz seu jogo avançar.', searchLabel: 'SteamID, nome do jogador ou URL do logs.tf', placeholder: 'SteamID, jogador ou URL do log', analyze: 'Analisar jogador', hint: 'Experimente um SteamID64, ID de log do logs.tf ou nome de jogador.', preview: 'Prévia dos analytics do TF2Lab', live: 'Insights da partida ao vivo', period: 'Últimos 30 dias', score: 'Pontuação de desempenho', matches: 'Partidas recentes', analyzed: '14 analisadas', features: 'O que o TF2Lab faz', pillars: 'Três pilares para jogadores competitivos', analytics: 'Analytics', analyticsText: 'Explore seus logs em profundidade — tendências de K/D, distribuição de dano, uso de classes e benchmarks por mapa e temporada.', analyticsCta: 'Ver analytics →', competition: 'Competições', competitionText: 'Acompanhe partidas oficiais, scrims e torneios. Analise adversários, gerencie escalações e prepare-se com dados.', competitionCta: 'Explorar partidas →', academy: 'Academia', academyText: 'Aprenda TF2 competitivo do zero — guias de configs, HUDs, whitelists, callouts de mapas e evolução de PUGs a ligas.', academyCta: 'Começar a aprender →', edge: 'Encontre sua vantagem', edgeText: 'Descubra o que vence mais rounds.', learn: 'Aprenda com cada partida', learnText: 'Transforme tendências em metas de treino.', built: 'Feito para TF2 competitivo', builtText: 'Focado, útil e gratuito.' },
    search: { breadcrumb: 'Busca', eyebrow: 'Busca do TF2Lab', title: 'Encontre jogadores e logs.', description: 'Busque por SteamID64, nome de jogador ou ID de log do logs.tf.', label: 'Buscar', placeholder: 'SteamID, jogador ou ID do log', clear: 'Limpar', searching: 'Buscando...', search: 'Buscar', help: 'Pressione / para focar a busca e Esc para limpar.', unavailable: 'Busca temporariamente indisponível', unavailableText: 'Não foi possível acessar o serviço de busca do logs.tf. Verifique sua conexão e tente novamente.', retry: 'Tentar novamente', primary: 'Resultados principais', players: 'Jogadores encontrados', exact: 'Correspondência exata', matches: 'Partidas', kills: 'Kills', damage: 'Dano', profile: 'Ver perfil do jogador →', secondary: 'Resultados secundários', related: 'Logs relacionados', hint: 'Encontramos logs relacionados, mas nenhum apelido correspondeu à busca. Tente outro alias ou o SteamID64.', log: 'Log', map: 'Mapa', viewLog: 'Ver log', playerProfile: 'Perfil do jogador', openLogs: 'Abrir no logs.tf ↗', noResults: 'Nenhum resultado para', tryDifferent: 'Tente outro SteamID, nome de jogador ou ID de log.', suggestions: 'Tente buscar por:', examples: 'Exemplos:', archive: 'Busque no arquivo de logs do TF2Lab', start: 'Digite um SteamID64, nome de jogador ou ID de log do logs.tf acima para começar.', previous: '← Anterior', page: 'Página', of: 'de', next: 'Próxima →', openLogs: 'Abrir no logs.tf ↗', pagination: 'Paginação', examples: 'Exemplos:', emptySteamId: 'Este SteamID64 não foi encontrado no logs.tf. Verifique se é um SteamID64 válido com 17 dígitos (começando com 7656119).', emptyLogId: 'O ID de log {id} não foi encontrado no logs.tf.', emptyPlayer: 'Nenhum jogador correspondeu a "{name}" na amostra do logs.tf. Tente um alias exato ou SteamID64 para encontrar o perfil.' },
    compare: { breadcrumb: 'Comparar', eyebrow: 'Comparação do TF2Lab', title: 'Compare dois jogadores.', description: 'Coloque dois SteamID64 lado a lado e veja onde cada jogador se destaca.', inputPlaceholder: 'Nome do jogador ou SteamID64', playerA: 'Jogador A', playerB: 'Jogador B', window: 'Janela', games: 'Últimos {n} jogos', compare: 'Comparar jogadores', comparing: 'Comparando...', clear: 'Limpar', loading: 'Carregando comparação', fullProfile: 'Ver perfil completo →', summary: 'Resumo rápido', leads: 'lidera em', table: 'Comparação de desempenho', metric: 'Métrica', matches: 'Partidas', kills: 'Kills', deaths: 'Mortes', damage: 'Dano', heals: 'Curas', choose: 'Escolha dois jogadores', chooseText: 'Use SteamID64 para criar uma comparação consistente entre perfis analisados pelo TF2Lab.', example: 'Exemplo:', loadExample: 'Carregar dois jogadores de exemplo', invalid: 'Informe dois SteamID64 válidos com 17 dígitos.', same: 'Escolha dois jogadores diferentes.', failed: 'Não foi possível carregar um dos perfis. Verifique os SteamID64 e tente novamente.', none: 'nenhum indicador' },
    player: { search: 'Buscar', back: 'Voltar para a busca', analysisWindow: 'Janela de análise', all: 'Todos', logs: 'logs', analysisWarning: 'A análise de tendência precisa de pelo menos {n} logs para ser confiável.', kdPerMatch: 'K/D por partida', damagePerMatch: 'Dano por partida', healingPerMatch: 'Cura por partida', damageByClass: 'Dano por classe', notFound: 'Jogador não encontrado', unavailable: 'Não há dados de desempenho analisados para', reason: 'Motivo:', checkSteam: 'Verifique o SteamID ou tente um jogador com logs públicos.', newSearch: 'Nova busca' },
    log: { search: 'Buscar', back: 'Voltar para a busca', notFound: 'Log não encontrado', unable: 'Não foi possível carregar o log', reason: 'Motivo:', checkId: 'Verifique o ID e tente novamente.', newSearch: 'Nova busca' }
  }
} as const

type Locale = 'en' | 'pt'

export function useLocale() {
  const savedLocale = useCookie<Locale | undefined>('tf2lab-locale', {
    default: () => undefined,
    sameSite: 'lax',
    maxAge: 60 * 60 * 24 * 365,
  })
  const browserLocale: Locale = import.meta.client && navigator.language.toLowerCase().startsWith('pt') ? 'pt' : 'en'
  const locale = useState<Locale>('tf2lab-locale-state', () => savedLocale.value ?? browserLocale)

  if (import.meta.client && !savedLocale.value) {
    savedLocale.value = browserLocale
  }

  const setLocale = (nextLocale: Locale) => {
    locale.value = nextLocale
    savedLocale.value = nextLocale
  }

  const t = computed(() => translations[locale.value])
  return { locale, setLocale, t }
}
export type Translations = typeof translations.en

